import React, { useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import web3Onboard from "../src/web3Onboard";
import WROSE from "../src/wrose";
import BalanceOf from "../components/BalanceOf";
import Deposit from "../components/Deposit";
import Withdraw from "../components/Withdraw";
import MetaWithdraw from "../components/MetaWithdraw";

export default function Home() {
  const [signer, setSigner] = useState(null);
  const [wrose, setWrose] = useState(null);

  async function connect() {
    const signer = await web3Onboard();
    setSigner(signer);
    setWrose(new WROSE(signer));
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>WROSE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button onClick={connect}>Connect</button>

      {signer ? (
        <>
          <BalanceOf wrose={wrose} />
          <Deposit wrose={wrose} />
          <Withdraw wrose={wrose} />
          <MetaWithdraw wrose={wrose} />
        </>
      ) : (
        <></>
      )}
    </div>
  );
}
